version: '3'
services:
  web:
    build: .
    ports:
      - "4000:5000"
    volumes:
      - ./webapp:/opt/webapp
    environment:
      - PORT=5000
      - FLASK_DEBUG=1
      - FLASK_APP=/opt/webapp/app.py