FROM continuumio/miniconda3

# Grab requirements.txt.
COPY ./webapp/requirements.txt /tmp/requirements.txt

# Install dependencies
RUN pip install -r /tmp/requirements.txt

# Add our code
ADD ./webapp /opt/webapp/
WORKDIR /opt/webapp

RUN conda install scikit-learn

CMD flask run --host=0.0.0.0
