version: '3'
services:
  web:
    build: .
    ports:
      - "4000:5000"
    volumes:
      - ./webapp:/opt/webapp
    environment:
      - PORT=5000
      - FLASK_APP=/opt/webapp/app.py
  dev:
    build: 
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "4000:5000"
    volumes:
      - ./webapp:/opt/webapp
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=/opt/webapp/app.py